version: '3.9'
services:
  backend:
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - femiarkh-network
  postgres:
    build: ./database/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_DIALECT: ${POSTGRES_DIALECT}
    networks:
      - femiarkh-network
networks:
  femiarkh-network:
    driver: bridge
