version: '3'
services:
  node:
    build: .
    ports:
      - 127.0.0.1:${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - ./src:/usr/app/src
      - ./logs:/usr/app/logs
    networks:
      - custom-network
    restart: always
    environment:
      - PORT=${PORT}
    image: femiarkh/rss-node
  postgres:
    build: ./database/
    ports:
      - 127.0.0.1:${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - custom-network
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    image: femiarkh/rss-postgres
networks:
  custom-network: {}
